version: "3.8"

services:
  naming:
    image: ubuntu20.04-opendds
    container_name: naming
    command: tao_cosnaming -ORBListenEndpoints iiop://0.0.0.0:2809
    networks:
      opendds_net:
        ipv4_address: 172.30.0.2

  info:
    image: ubuntu20.04-opendds
    container_name: info
    depends_on: [naming]
    command: >
      bash -c "
        sleep 2 &&
        DCPSInfoRepo
          -NOBITS
          -ORBInitRef NameService=corbaloc::naming:2809/NameService
          -ORBListenEndpoints iiop://0.0.0.0:12345"
    networks:
      opendds_net:
        ipv4_address: 172.30.0.3

  subscriber:
    image: ubuntu20.04-opendds
    container_name: sub
    depends_on: [info]
    working_dir: /workspace/examples/messenger/build
    volumes:
      - .:/workspace/examples/messenger
    command: >
      bash -c "
        sleep 4 &&
        ./subscriber
          -ORBInitRef NameService=corbaloc::naming:2809/NameService
          -DCPSInfoRepo corbaloc::info:12345/DCPSInfoRepo"
    networks:
      opendds_net:
        ipv4_address: 172.30.0.4

  publisher:
    image: ubuntu20.04-opendds
    container_name: pub
    depends_on: [info]
    working_dir: /workspace/examples/messenger/build


networks:
  opendds_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16    
